-- Idempotent first migration. Data is tenant scoped; keys and expiry have dedicated indexes.

CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS users_owner_idx ON users(owner);
CREATE INDEX IF NOT EXISTS users_expiry_idx ON users(expires_at);
CREATE TABLE IF NOT EXISTS credentials (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS credentials_owner_idx ON credentials(owner);
CREATE INDEX IF NOT EXISTS credentials_expiry_idx ON credentials(expires_at);
CREATE TABLE IF NOT EXISTS challenges (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS challenges_owner_idx ON challenges(owner);
CREATE INDEX IF NOT EXISTS challenges_expiry_idx ON challenges(expires_at);
CREATE TABLE IF NOT EXISTS auth_sessions (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS auth_sessions_owner_idx ON auth_sessions(owner);
CREATE INDEX IF NOT EXISTS auth_sessions_expiry_idx ON auth_sessions(expires_at);
CREATE TABLE IF NOT EXISTS refresh_tokens (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS refresh_tokens_owner_idx ON refresh_tokens(owner);
CREATE INDEX IF NOT EXISTS refresh_tokens_expiry_idx ON refresh_tokens(expires_at);
CREATE TABLE IF NOT EXISTS recovery_codes (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS recovery_codes_owner_idx ON recovery_codes(owner);
CREATE INDEX IF NOT EXISTS recovery_codes_expiry_idx ON recovery_codes(expires_at);
CREATE TABLE IF NOT EXISTS pairing_codes (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS pairing_codes_owner_idx ON pairing_codes(owner);
CREATE INDEX IF NOT EXISTS pairing_codes_expiry_idx ON pairing_codes(expires_at);
CREATE TABLE IF NOT EXISTS devices (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS devices_owner_idx ON devices(owner);
CREATE INDEX IF NOT EXISTS devices_expiry_idx ON devices(expires_at);
CREATE TABLE IF NOT EXISTS sessions (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS sessions_owner_idx ON sessions(owner);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS events (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS events_owner_idx ON events(owner);
CREATE INDEX IF NOT EXISTS events_expiry_idx ON events(expires_at);
CREATE TABLE IF NOT EXISTS approvals (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS approvals_owner_idx ON approvals(owner);
CREATE INDEX IF NOT EXISTS approvals_expiry_idx ON approvals(expires_at);
CREATE TABLE IF NOT EXISTS commands (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS commands_owner_idx ON commands(owner);
CREATE INDEX IF NOT EXISTS commands_expiry_idx ON commands(expires_at);
CREATE TABLE IF NOT EXISTS usage (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS usage_owner_idx ON usage(owner);
CREATE INDEX IF NOT EXISTS usage_expiry_idx ON usage(expires_at);
CREATE TABLE IF NOT EXISTS audit (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS audit_owner_idx ON audit(owner);
CREATE INDEX IF NOT EXISTS audit_expiry_idx ON audit(expires_at);
CREATE TABLE IF NOT EXISTS push_subscriptions (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS push_subscriptions_owner_idx ON push_subscriptions(owner);
CREATE INDEX IF NOT EXISTS push_subscriptions_expiry_idx ON push_subscriptions(expires_at);
CREATE TABLE IF NOT EXISTS push_settings (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS push_settings_owner_idx ON push_settings(owner);
CREATE INDEX IF NOT EXISTS push_settings_expiry_idx ON push_settings(expires_at);
CREATE TABLE IF NOT EXISTS ws_tickets (id text PRIMARY KEY, owner text NOT NULL, data jsonb NOT NULL, created_at bigint NOT NULL, expires_at bigint);
CREATE INDEX IF NOT EXISTS ws_tickets_owner_idx ON ws_tickets(owner);
CREATE INDEX IF NOT EXISTS ws_tickets_expiry_idx ON ws_tickets(expires_at);
CREATE INDEX IF NOT EXISTS events_session_seq_idx ON events (owner, (data->>'sessionId'), ((data->>'seq')::bigint));
CREATE INDEX IF NOT EXISTS usage_dimensions_idx ON usage (owner, (data->>'deviceId'), (data->>'agent'), (data->>'project'));
CREATE INDEX IF NOT EXISTS commands_device_idx ON commands (owner, (data->>'deviceId'));
CREATE INDEX IF NOT EXISTS approvals_pending_idx ON approvals (owner, (data->>'status'));
